local ffi = require("ffi")

scriptHook.Remove(engine.Classes.UItemInspectionGFxMovie.funcs.InspectItem, "InspectHook")
scriptHook.Add(engine.Classes.UItemInspectionGFxMovie.funcs.InspectItem, "InspectHok", function(Object, Stack, Result, Function)
	print("InspectItem called")

	local thing = Stack:GetStruct("struct AWillowInventory*")
	print(thing:GetFullName())
	
	print("WillowInventory members")

	print(thing.MonetaryValue)
	print(thing.Quantity)
	print(thing.RarityLevel)
	print(thing.ExpLevel)
	print(thing.GameStage)
	print(thing.AwesomeLevel)
	print(thing.ClonedForSharing)
	print(thing.ItemLocation)
	print(thing.Mark)

	print(thing.ZippyFrame:GetName())
	print(thing.ItemFrame:GetLuaString())
	print(thing.ElementalFrame:GetName())
	print(thing.SourceDefinitionName:GetName())
	print(thing.SourceResponsibleName:GetName())

	print("WillowWeapon members")
	print(thing.ShotCost)
	print(thing.ShotCostBaseValue)
	print(thing.AdditionalRicochets)
	print(thing.AdditionalRicochetsBaseValue)
	print(thing.ClipSize)
	print(thing.ClipSizeBaseValue)
	print(thing.ReloadTime)
	print(thing.ReloadTimeBaseValue)
	print(thing.bUseWeaponMelee)

	print(thing:GenerateHumanReadableName():GetLuaString())

end)

local function GetWeaponTypes()
	local weaponTypes = {}

	for i=0,(engine.Objects.Count-1) do
		local obj = engine.Objects:Get(i)
		if IsNull(obj) then goto continue end
		if obj.UObject.Class ~= engine.Classes.UWeaponTypeDefinition.static then goto continue end

		obj = ffi.cast("struct UWeaponTypeDefinition*", obj)

		table.insert(weaponTypes, obj)
		print(obj:GetFullName())

		::continue::
	end

	table.remove(weaponTypes, 1)

	return weaponTypes
end




--[[
struct AWillowWeapon_Data {
	struct FPointer VfTable_IIInstanceData; // 0x9AC (0x4)
	struct FPointer VfTable_IIMissionInventory; // 0x9B0 (0x4)
	struct FPointer VfTable_IIBehaviorConsumer; // 0x9B4 (0x4)
	struct FPointer VfTable_IIItemCardable; // 0x9B8 (0x4)
	struct FPointer VfTable_IINounAttributeProvider; // 0x9BC (0x4)
	int NextFiringPatternIndex; // 0x9C0 (0x4)
	int StoredAmmo; // 0x9C4 (0x4)
	struct FResourcePoolReference AmmoPool; // 0x9C8 (0xC)
	int AmmoNotInClip; // 0x9D4 (0x4)
	bool bUpdateAmmoNotInClip : 1; // 0x9D8 (0x4)
	bool bAmmoRefilledDuringReload : 1; // 0x9D8 (0x4)
	bool bItemNameGenerated : 1; // 0x9D8 (0x4)
	bool bUseOverheatBehavior : 1; // 0x9D8 (0x4)
	bool bBurstDelayActive : 1; // 0x9D8 (0x4)
	bool bDisplayWeaponShotDebug : 1; // 0x9D8 (0x4)
	bool bDisableFireViewShake : 1; // 0x9D8 (0x4)
	bool bDisableWeaponSpread : 1; // 0x9D8 (0x4)
	bool bHoldToZoom : 1; // 0x9D8 (0x4)
	bool bFadeOnZoomBegin : 1; // 0x9D8 (0x4)
	bool bFadeOnZoomEnd : 1; // 0x9D8 (0x4)
	bool bDeRezzed : 1; // 0x9D8 (0x4)
	bool bReplicateFiringSounds : 1; // 0x9D8 (0x4)
	bool bSwappingWeaponAfterPutDown : 1; // 0x9D8 (0x4)
	bool bMuzzleFlashPSCLoops : 1; // 0x9D8 (0x4)
	bool bSelectRandomPartsOnInitialization : 1; // 0x9D8 (0x4)
	bool bInitAnimationsOnAttach : 1; // 0x9D8 (0x4)
	bool bContinuousBeamIsFiring : 1; // 0x9D8 (0x4)
	bool bCrosshairEnabled : 1; // 0x9D8 (0x4)
	bool bSuppressCrosshair : 1; // 0x9D8 (0x4)
	bool bIsBlockedAfterBusy : 1; // 0x9D8 (0x4)
	bool bUseRealTimeForZoom : 1; // 0x9D8 (0x4)
	bool bAttachedToInstigator : 1; // 0x9D8 (0x4)
	bool bHolsteredOnBody : 1; // 0x9D8 (0x4)
	bool bActivatedDuringVehicleTransition : 1; // 0x9D8 (0x4)
	bool bOnlyPlayFirstPersonAnimOnNextEquip : 1; // 0x9D8 (0x4)
	int ShotCost; // 0x9DC (0x4)
	int ShotCostBaseValue; // 0x9E0 (0x4)
	struct TArray_UAttributeModifierPtr_ ShotCostModifierStack; // 0x9E4 (0xC)
	int AdditionalRicochets; // 0x9F0 (0x4)
	int AdditionalRicochetsBaseValue; // 0x9F4 (0x4)
	struct TArray_UAttributeModifierPtr_ AdditionalRicochetsModifierStack; // 0x9F8 (0xC)
	float LastFireTime; // 0xA04 (0x4)
	int ClipSize; // 0xA08 (0x4)
	int ClipSizeBaseValue; // 0xA0C (0x4)
	struct TArray_UAttributeModifierPtr_ ClipSizeModifierStack; // 0xA10 (0xC)
	int LastReloadCnt; // 0xA1C (0x4)
	int LastClipSize; // 0xA20 (0x4)
	int AmmoLeftInClipDuringReload; // 0xA24 (0x4)
	int ReloadCnt; // 0xA28 (0x4)
	int CurrentBurstShotCount; // 0xA2C (0x4)
	float ReloadTime; // 0xA30 (0x4)
	float ReloadTimeBaseValue; // 0xA34 (0x4)
	struct TArray_UAttributeModifierPtr_ ReloadTimeModifierStack; // 0xA38 (0xC)
	unsigned char ReplicatedReloadState; // 0xA44 (0x1)
	unsigned char bUseWeaponMelee; // 0xA45 (0x1)
	unsigned char ZoomState; // 0xA46 (0x1)
	unsigned char BodyVariation; // 0xA47 (0x1)
	unsigned char PutDownAnimState; // 0xA48 (0x1)
	unsigned char MagazineSpinState; // 0xA49 (0x1)
	unsigned char LastProcessedMagazineSpinState; // 0xA4A (0x1)
	unsigned char BarrelSpinState; // 0xA4B (0x1)
	unsigned char LastProcessedBarrelSpinState; // 0xA4C (0x1)
	unsigned char VisibleAmmoState; // 0xA4D (0x1)
	unsigned char QuickSelectSlot; // 0xA4E (0x1)
	struct USpecialMoveDefinition* Playing1stPersonReloadSMD; // 0xA50 (0x4)
	struct USpecialMoveDefinition* Playing3rdPersonReloadSMD; // 0xA54 (0x4)
	struct FString GeneratedItemName; // 0xA58 (0xC)
	float OverheatRegenDelay; // 0xA64 (0x4)
	float OverheatRegenDelayBaseValue; // 0xA68 (0x4)
	struct TArray_UAttributeModifierPtr_ OverheatRegenDelayModifierStack; // 0xA6C (0xC)
	float FireRegenDelay; // 0xA78 (0x4)
	float FireRegenDelayBaseValue; // 0xA7C (0x4)
	struct TArray_UAttributeModifierPtr_ FireRegenDelayModifierStack; // 0xA80 (0xC)
	float RegenRate; // 0xA8C (0x4)
	float RegenRateBaseValue; // 0xA90 (0x4)
	struct TArray_UAttributeModifierPtr_ RegenRateModifierStack; // 0xA94 (0xC)
	float RegenAmount; // 0xAA0 (0x4)
	int OverheatAmmo; // 0xAA4 (0x4)
	float AmmoRegenStartTime; // 0xAA8 (0x4)
	float MeleeDamage; // 0xAAC (0x4)
	float MeleeDamageBaseValue; // 0xAB0 (0x4)
	struct TArray_UAttributeModifierPtr_ MeleeDamageModifierStack; // 0xAB4 (0xC)
	float NormalizedInstantHitDamage; // 0xAC0 (0x4)
	float NormalizedInstantHitDamageBaseValue; // 0xAC4 (0x4)
	struct TArray_UAttributeModifierPtr_ NormalizedInstantHitDamageModifierStack; // 0xAC8 (0xC)
	float NormalizedMeleeDamage; // 0xAD4 (0x4)
	float NormalizedMeleeDamageBaseValue; // 0xAD8 (0x4)
	struct TArray_UAttributeModifierPtr_ NormalizedMeleeDamageModifierStack; // 0xADC (0xC)
	float BurstInterval; // 0xAE8 (0x4)
	float BurstIntervalBaseValue; // 0xAEC (0x4)
	struct TArray_UAttributeModifierPtr_ BurstIntervalModifierStack; // 0xAF0 (0xC)
	int AutomaticBurstCount; // 0xAFC (0x4)
	int AutomaticBurstCountBaseValue; // 0xB00 (0x4)
	struct TArray_UAttributeModifierPtr_ AutomaticBurstCountModifierStack; // 0xB04 (0xC)
	float BurstShotAccuracyImpulseScale; // 0xB10 (0x4)
	float BurstShotAccuracyImpulseScaleBaseValue; // 0xB14 (0x4)
	struct TArray_UAttributeModifierPtr_ BurstShotAccuracyImpulseScaleModifierStack; // 0xB18 (0xC)
	float LastAutomaticBurstTime; // 0xB24 (0x4)
	struct FInstanceDataSet InstanceDataState; // 0xB28 (0xC)
	struct TArray_AWeaponShotDebugPtr_ WeaponShotDebugHistory; // 0xB34 (0xC)
	float BaseStatusEffectChanceModifier; // 0xB40 (0x4)
	float BaseStatusEffectChanceModifierBaseValue; // 0xB44 (0x4)
	struct TArray_UAttributeModifierPtr_ BaseStatusEffectChanceModifierModifierStack; // 0xB48 (0xC)
	float StatusEffectChanceModifier; // 0xB54 (0x4)
	float StatusEffectChanceModifierBaseValue; // 0xB58 (0x4)
	struct TArray_UAttributeModifierPtr_ StatusEffectChanceModifierModifierStack; // 0xB5C (0xC)
	float StatusEffectSpreadTimeIntervalModifier; // 0xB68 (0x4)
	float StatusEffectSpreadTimeIntervalModifierBaseValue; // 0xB6C (0x4)
	struct TArray_UAttributeModifierPtr_ StatusEffectSpreadTimeIntervalModifierModifierStack; // 0xB70 (0xC)
	float StatusEffectDamage; // 0xB7C (0x4)
	float StatusEffectDamageBaseValue; // 0xB80 (0x4)
	struct TArray_UAttributeModifierPtr_ StatusEffectDamageModifierStack; // 0xB84 (0xC)
	float ZoomedEndFOV; // 0xB90 (0x4)
	float ZoomedEndFOVBaseValue; // 0xB94 (0x4)
	struct TArray_UAttributeModifierPtr_ ZoomedEndFOVModifierStack; // 0xB98 (0xC)
	float ZoomedFOV; // 0xBA4 (0x4)
	float ZoomedRate; // 0xBA8 (0x4)
	float ZoomedRateBaseValue; // 0xBAC (0x4)
	struct TArray_UAttributeModifierPtr_ ZoomedRateModifierStack; // 0xBB0 (0xC)
	float ZoomFadeTime; // 0xBBC (0x4)
	float ZoomStartTime; // 0xBC0 (0x4)
	struct UMaterialInstance* WeaponMaterial; // 0xBC4 (0x4)
	struct UMaterialInstance* SightFXCrosshairMaterial; // 0xBC8 (0x4)
	struct USkeletalMeshComponent* ThirdPersonMesh; // 0xBCC (0x4)
	int CurrentSlot; // 0xBD0 (0x4)
	struct TArray_FExtraWeaponSlot_ ExtraSlots; // 0xBD4 (0xC)
	struct FVector CachedMuzzleLocation; // 0xBE0 (0xC)
	int CachedMuzzleLocationFrameNumber; // 0xBEC (0x4)
	struct USkeletalMeshComponent* CachedMuzzleLocationMesh; // 0xBF0 (0x4)
	struct UWillowAnimNodeSlot* WeaponAnimNodeSlot; // 0xBF4 (0x4)
	struct UWillowAnimNodeSlot* ArmAnimNodeSlot; // 0xBF8 (0x4)
	struct UAkEvent* BulletWhipAkEvent; // 0xBFC (0x4)
	struct FImpactResponseParameters MyWeaponImpactResponseParameters; // 0xC00 (0x4C)
	float MagazineSpinUpDuration; // 0xC4C (0x4)
	float MagazineSpinUpDurationBaseValue; // 0xC50 (0x4)
	struct TArray_UAttributeModifierPtr_ MagazineSpinUpDurationModifierStack; // 0xC54 (0xC)
	float MagazineSpinDownDuration; // 0xC60 (0x4)
	float MagazineSpinDownDurationBaseValue; // 0xC64 (0x4)
	struct TArray_UAttributeModifierPtr_ MagazineSpinDownDurationModifierStack; // 0xC68 (0xC)
	float MagazineSpinUpPercent; // 0xC74 (0x4)
	float BodyFlapsExpandDuration; // 0xC78 (0x4)
	float BodyFlapsExpandDurationBaseValue; // 0xC7C (0x4)
	struct TArray_UAttributeModifierPtr_ BodyFlapsExpandDurationModifierStack; // 0xC80 (0xC)
	float BodyFlapsCollapseDuration; // 0xC8C (0x4)
	float BodyFlapsCollapseDurationBaseValue; // 0xC90 (0x4)
	struct TArray_UAttributeModifierPtr_ BodyFlapsCollapseDurationModifierStack; // 0xC94 (0xC)
	float BarrelFlapsExpandDuration; // 0xCA0 (0x4)
	float BarrelFlapsExpandDurationBaseValue; // 0xCA4 (0x4)
	struct TArray_UAttributeModifierPtr_ BarrelFlapsExpandDurationModifierStack; // 0xCA8 (0xC)
	float BarrelFlapsCollapseDuration; // 0xCB4 (0x4)
	float BarrelFlapsCollapseDurationBaseValue; // 0xCB8 (0x4)
	struct TArray_UAttributeModifierPtr_ BarrelFlapsCollapseDurationModifierStack; // 0xCBC (0xC)
	float BaseGlowScale; // 0xCC8 (0x4)
	float FinalGlowScale; // 0xCCC (0x4)
	struct UWeaponGlowEffectDefinition* GlowEffect; // 0xCD0 (0x4)
	float GlowEffectStartTime; // 0xCD4 (0x4)
	float GlowImpulseScale; // 0xCD8 (0x4)
	float GlowImpulseDecayStartTime; // 0xCDC (0x4)
	struct UParticleSystemComponent* FirstPersonMuzzleFlash; // 0xCE0 (0x4)
	struct TArray_UParticleSystemComponentPtr_ FirstPersonAltMuzzleFlashes; // 0xCE4 (0xC)
	struct UParticleSystemComponent* ThirdPersonMuzzleFlash; // 0xCF0 (0x4)
	struct TArray_UParticleSystemComponentPtr_ ThirdPersonAltMuzzleFlashes; // 0xCF4 (0xC)
	int NumberOfMuzzleFlashes; // 0xD00 (0x4)
	int CurrentMuzzleFlashIndex; // 0xD04 (0x4)
	struct UParticleSystemComponent* FirstPersonShellCasing; // 0xD08 (0x4)
	struct UWillowPointLight* MuzzleFlashLight; // 0xD0C (0x4)
	struct UWillowPointLight* ThirdPersonMuzzleFlashLight; // 0xD10 (0x4)
	struct UParticleSystemComponent* TracerParameterTemplate; // 0xD14 (0x4)
	struct UParticleSystem* MuzzleFlashPSTemplate; // 0xD18 (0x4)
	float CurrentRating; // 0xD1C (0x4)
	int OwnerStatsID; // 0xD20 (0x4)
	int WeaponStatsID; // 0xD24 (0x4)
	float ExtraShotChance; // 0xD28 (0x4)
	float ExtraShotChanceBaseValue; // 0xD2C (0x4)
	struct TArray_UAttributeModifierPtr_ ExtraShotChanceModifierStack; // 0xD30 (0xC)
	float ExtraShotDelay; // 0xD3C (0x4)
	float ExtraShotDelayBaseValue; // 0xD40 (0x4)
	struct TArray_UAttributeModifierPtr_ ExtraShotDelayModifierStack; // 0xD44 (0xC)
	struct FLockOnTargetStateStruct LockOnTargetState; // 0xD50 (0x10)
	float BarrelSpinUpDuration; // 0xD60 (0x4)
	float BarrelSpinUpDurationBaseValue; // 0xD64 (0x4)
	struct TArray_UAttributeModifierPtr_ BarrelSpinUpDurationModifierStack; // 0xD68 (0xC)
	float BarrelSpinDownDuration; // 0xD74 (0x4)
	float BarrelSpinDownDurationBaseValue; // 0xD78 (0x4)
	struct TArray_UAttributeModifierPtr_ BarrelSpinDownDurationModifierStack; // 0xD7C (0xC)
	float BarrelSpinUpPercent; // 0xD88 (0x4)
	struct FColor WeaponColor; // 0xD8C (0x4)
	float AimError; // 0xD90 (0x4)
	float AimErrorBaseValue; // 0xD94 (0x4)
	struct TArray_UAttributeModifierPtr_ AimErrorModifierStack; // 0xD98 (0xC)
	float PerShotAccuracyImpulse; // 0xDA4 (0x4)
	float PerShotAccuracyImpulseBaseValue; // 0xDA8 (0x4)
	struct TArray_UAttributeModifierPtr_ PerShotAccuracyImpulseModifierStack; // 0xDAC (0xC)
	int ProjectilesPerShot; // 0xDB8 (0x4)
	int ProjectilesPerShotBaseValue; // 0xDBC (0x4)
	struct TArray_UAttributeModifierPtr_ ProjectilesPerShotModifierStack; // 0xDC0 (0xC)
	struct TArray_FAppliedAttributeEffect_ ExternalAttributeModifiers; // 0xDCC (0xC)
	struct TArray_FAppliedAttributeEffect_ WeaponAttributeModifiers; // 0xDD8 (0xC)
	struct TArray_FAppliedAttributeEffect_ ZoomExternalAttributeModifiers; // 0xDE4 (0xC)
	struct TArray_FAppliedAttributeEffect_ ZoomWeaponAttributeModifiers; // 0xDF0 (0xC)
	struct TArray_FModifierValuePresentationData_ WeaponCardModifierStats; // 0xDFC (0xC)
	struct FReplicatedInventoryCardData ReplicatedWeaponCardModifierValues[5]; // 0xE08 (0x28)
	struct FWeaponDefinitionData DefinitionData; // 0xE30 (0x44)
	struct UWeaponPartListCollectionDefinition* PartListCollection; // 0xE74 (0x4)
	struct TArray_FWeaponBoneControllerInstance_ WeaponPartBoneControllers; // 0xE78 (0xC)
	int ReloadCntOnLastVisibleAmmoBoneUpdate; // 0xE84 (0x4)
	struct TArray_unsigned_char_ VisibleAmmoBoneIndices; // 0xE88 (0xC)
	struct FName LeftHandGripAnimWeapon; // 0xE94 (0x8)
	struct AWillowWeapon* LastComparedWeapon; // 0xE9C (0x4)
	struct FName StoredPreviousStateName; // 0xEA0 (0x8)
	struct TArray_FShellCasingImpact_ ShellCasingImpacts; // 0xEA8 (0xC)
	float ProjectileSpeedMultiplier; // 0xEB4 (0x4)
	float ProjectileSpeedMultiplierBaseValue; // 0xEB8 (0x4)
	struct TArray_UAttributeModifierPtr_ ProjectileSpeedMultiplierModifierStack; // 0xEBC (0xC)
	float UpdateMipTimer; // 0xEC8 (0x4)
	float WantsMissedShotNotifications; // 0xECC (0x4)
	float WantsMissedShotNotificationsBaseValue; // 0xED0 (0x4)
	struct TArray_UAttributeModifierPtr_ WantsMissedShotNotificationsModifierStack; // 0xED4 (0xC)
	struct FBehaviorConsumerHandle ConsumerHandle; // 0xEE0 (0x4)
	struct TArray_FNounAttributeState_ NounState; // 0xEE4 (0xC)
	float TotalAutomaticFiringTime; // 0xEF0 (0x4)
	struct FImpactInfo LastLocalHitTraceInfo; // 0xEF4 (0x5C)
	struct FString CrosshairFrameOverride; // 0xF50 (0xC)
};

struct AInventory_Data {
	struct AInventory* Inventory; // 0x188 (0x4)
	struct AInventoryManager* InvManager; // 0x18C (0x4)
	struct FString ItemName; // 0x190 (0xC)
	bool bDropOnDeath : 1; // 0x19C (0x4)
	bool bReadied : 1; // 0x19C (0x4)
	bool bDelayedSpawn : 1; // 0x19C (0x4)
	bool bPredictRespawns : 1; // 0x19C (0x4)
	unsigned char Unknown0[0x3]; // BITFIELD FIX
	float RespawnTime; // 0x1A0 (0x4)
	float MaxDesireability; // 0x1A4 (0x4)
	struct FString PickupMessage; // 0x1A8 (0xC)
	struct ULocalMessage* MessageClass; // 0x1B4 (0x4)
	struct USoundCue* PickupSound; // 0x1B8 (0x4)
	struct ADroppedPickup* DroppedPickupClass; // 0x1BC (0x4)
	struct UPrimitiveComponent* DroppedPickupMesh; // 0x1C0 (0x4)
	struct UPrimitiveComponent* PickupFactoryMesh; // 0x1C4 (0x4)
};

struct AWillowInventory_Data {
	struct FPointer VfTable_IIBalancedActor; // 0x1C8 (0x4)
	struct FPointer VfTable_IIAttributeSlotEffectProvider; // 0x1CC (0x4)
	int MonetaryValue; // 0x1D0 (0x4)
	float MonetaryValueModifierTotal; // 0x1D4 (0x4)
	int Quantity; // 0x1D8 (0x4)
	int RarityLevel; // 0x1DC (0x4)
	int ExpLevel; // 0x1E0 (0x4)
	int GameStage; // 0x1E4 (0x4)
	int AwesomeLevel; // 0x1E8 (0x4)
	struct UObject* AdditionalQueryInterfaceSource; // 0x1EC (0x4)
	float ClonedForSharing; // 0x1F0 (0x4)
	int LastCanBeUsedByResult; // 0x1F4 (0x4)
	struct FName ZippyFrame; // 0x1F8 (0x8)
	struct FString ItemFrame; // 0x200 (0xC)
	struct FName ElementalFrame; // 0x20C (0x8)
	struct FName SourceDefinitionName; // 0x214 (0x8)
	struct FName SourceResponsibleName; // 0x21C (0x8)
	unsigned char ItemLocation; // 0x224 (0x1)
	unsigned char Mark; // 0x225 (0x1)
	bool bShopsHaveInfiniteQuantity : 1; // 0x228 (0x4)
	bool bOnlyCompareStatsForMatchingAttributes : 1; // 0x228 (0x4)
	unsigned char Unknown0[0x3]; // BITFIELD FIX
	struct FAttributeSlotData AttributeSlots[19]; // 0x22C (0x5F0)
	float ReplicatedAttributeSlotModifierValues[19]; // 0x81C (0x4C)
	struct UGBXDefinition* RuntimeAttributeSlotSkill; // 0x868 (0x4)
	float TempStatModifier; // 0x86C (0x4)
	float TempStatModifierBaseValue; // 0x870 (0x4)
	struct TArray_UAttributeModifierPtr_ TempStatModifierModifierStack; // 0x874 (0xC)
	struct TArray_FAppliedAttributeEffect_ AppliedAttributeSlotEffects; // 0x880 (0xC)
	struct TArray_AActorPtr_ ExternalLikenessConsumers; // 0x88C (0xC)
};
]]